_default:
    just --list

build MODE='':
    maturin build {{MODE}}

develop:
    maturin develop

test:
    maturin develop
    cargo run -p lutra-cli -- \
        codegen --project=tests/types.lt tests/types_generated.py
    ty check tests python/lutra_bin
    ruff check tests python/lutra_bin
    python -m unittest tests/main.py
