_default:
    just --list

build_opts := "--target-dir=../../target/wheels --uv"

build MODE='':
    maturin build {{build_opts}} {{MODE}}

develop:
    maturin develop {{build_opts}}

test:
    maturin develop {{build_opts}} --quiet

    # lutra codegen
    cargo run -p lutra-cli --quiet -- \
      codegen --project=tests/lutra.lt tests/lutra_generated.py --programs-sql-pg ''

    # check
    ty check python/lutra_runner_postgres tests
    ruff check python/lutra_runner_postgres tests

    # tests
    usql postgres://postgres:pass@localhost:5416 -f tests/init.sql
    python -m unittest tests/main.py
