_default:
    just --list

build MODE='':
    maturin build {{MODE}}

develop:
    maturin develop

test:
    maturin develop

    # lutra codegen
    cargo run -p lutra-cli -- \
      codegen --project=tests/lutra.lt tests/lutra_generated.py --programs-sql-pg ''

    # check
    ty check python/lutra_runner_postgres tests
    ruff check python/lutra_runner_postgres tests

    # tests
    usql postgres://postgres:pass@localhost:5416 -f tests/init.sql
    python -m unittest tests/main.py
