_default:
    just --list

build:
    maturin build

develop:
    maturin develop

release:
    maturin release

test:
    just develop
    cargo run -p lutra-cli -- codegen tests/lutra.lt tests/lutra_generated.py --sr-modules ''
    python -m mypy python/lutra_runner_postgres tests
    python -m unittest tests/main.py
