use std::collections::{HashMap, VecDeque};
use std::fs;
use std::path::PathBuf;
use std::{borrow::Cow, fmt::Write};

use lutra_bin::{ir, layout, Encode};
use lutra_compiler::{pr, CompileParams, DiscoverParams, Project};

#[track_caller]
pub fn generate(
    project_dir: &std::path::Path,
    out_file: &std::path::Path,
    options: super::GenerateOptions,
) -> Vec<PathBuf> {
    // tracing_subscriber::fmt::Subscriber::builder()
    // .without_time()
    // .with_max_level(tracing::Level::TRACE)
    // .try_init()
    // .ok();

    // discover the project
    let source = lutra_compiler::discover(DiscoverParams {
        project_path: project_dir.into(),
    })
    .unwrap();

    // compile
    let project =
        lutra_compiler::compile(source, CompileParams {}).unwrap_or_else(|e| panic!("{e}"));

    // generate
    let mut file = fs::File::create(out_file).unwrap();
    let out_dir = out_file.parent().unwrap().to_path_buf();
    let generated = codegen_main(&project, out_dir, &options).unwrap();
    std::io::Write::write_all(&mut file, generated.as_bytes()).unwrap();

    // return vec of input files
    project.source.get_sources().map(|s| s.0.clone()).collect()
}

#[derive(Debug)]
pub struct Context<'a> {
    current_rust_mod: Vec<String>,

    /// Buffer for types that don't have their own Lutra decl, but need their own Rust decl.
    /// When such type ref is encountered, it is pushed into here and generated later.
    def_buffer: VecDeque<ir::Ty>,

    // static env
    options: &'a super::GenerateOptions,
    ty_defs: &'a HashMap<ir::Path, &'a ir::Ty>,
    project: &'a Project,
    #[allow(dead_code)]
    out_dir: PathBuf,
}

impl<'a> Context<'a> {
    fn is_done(&self) -> bool {
        self.def_buffer.is_empty()
    }

    #[allow(dead_code)]
    fn get_ty_mat<'t: 'a>(&'t self, ty: &'t ir::Ty) -> &'t ir::Ty {
        if let ir::TyKind::Ident(path) = &ty.kind {
            self.ty_defs.get(path).unwrap()
        } else {
            ty
        }
    }
}

fn codegen_main(
    project: &Project,
    out_dir: PathBuf,
    options: &super::GenerateOptions,
) -> Result<String, std::fmt::Error> {
    use std::fmt::Write;

    let module = lutra_compiler::lower_type_defs(&project.root_module);
    let module = lutra_compiler::layouter::on_root_module(module);

    let ty_defs = module.iter_types_re().collect();

    let mut w = String::new();
    writeln!(w, "# Generated by lutra-codegen\n")?;
    writeln!(w, "import base64  # noqa: F401")?;
    writeln!(w, "import dataclasses  # noqa: F401")?;
    writeln!(w, "import functools  # noqa: F401")?;
    writeln!(w, "import typing  # noqa: F401")?;
    writeln!(w)?;
    writeln!(w, "import lutra_bin")?;
    writeln!(w)?;

    let mut ctx = Context {
        current_rust_mod: vec![],
        def_buffer: VecDeque::new(),

        options,
        ty_defs: &ty_defs,
        project,
        out_dir,
    };

    let module_path = vec![];
    codegen_module(&mut w, &module, module_path, &mut ctx)?;
    Ok(w)
}

fn codegen_module(
    w: &mut impl std::fmt::Write,
    module: &ir::Module,
    module_path: Vec<String>,
    ctx: &mut Context,
) -> Result<(), std::fmt::Error> {
    // collect decls
    let mut tys = Vec::new();
    let mut functions = Vec::new();
    let mut sub_modules = Vec::new();

    // iterate pr decls (which keep the order in the source)
    let root_mod = &ctx.project.root_module;
    let pr_mod = root_mod.module.get_submodule(&module_path).unwrap();
    for (name, pr_decl) in &pr_mod.names {
        let Some(decl) = module.decls.iter().find(|d| &d.name == name) else {
            continue;
        };

        match &decl.decl {
            ir::Decl::Module(module) => {
                sub_modules.push((name, module));
            }
            ir::Decl::Type(ty) => {
                let mut ty = ty.clone();
                super::infer_names(name, &mut ty);

                tys.push((ty, pr_decl.annotations.as_slice()));
            }
            ir::Decl::Var(ty) => {
                let mut ty = ty.clone();
                super::infer_names(name, &mut ty);

                if let ir::TyKind::Function(func) = ty.kind {
                    functions.push((name, *func));
                }
            }
        }
    }

    ctx.current_rust_mod = module_path.clone();

    // write types
    write_tys(w, tys, ctx)?;

    // write traits for functions
    let module_path_str = module_path.as_slice().join("::");
    if ctx.options.generate_sr_modules.contains(&module_path_str) {
        write_sr_programs(w, &functions, ctx)?;

        write_tys_in_buffer(w, ctx)?;
    }

    // recurse into sub modules
    for (name, sub_mod) in sub_modules {
        writeln!(w, "pub mod {name} {{")?;

        let mut path = module_path.clone();
        path.push(name.clone());
        codegen_module(w, sub_mod, path, ctx)?;
        writeln!(w, "}}\n")?;
    }

    assert!(ctx.is_done(), "{ctx:?}");

    Ok(())
}

pub fn write_tys(
    w: &mut impl Write,
    tys: Vec<(ir::Ty, &[pr::Annotation])>,
    ctx: &mut Context,
) -> Result<Vec<ir::Ty>, std::fmt::Error> {
    let mut all_tys = Vec::new();

    for (ty, annotations) in tys {
        write_ty_def(w, &ty, annotations, ctx)?;
        all_tys.push(ty);

        all_tys.extend(write_tys_in_buffer(w, ctx)?);
    }
    Ok(all_tys)
}

pub fn write_tys_in_buffer(
    w: &mut impl Write,
    ctx: &mut Context<'_>,
) -> Result<Vec<ir::Ty>, std::fmt::Error> {
    let mut all_tys = Vec::new();
    while let Some(ty) = ctx.def_buffer.pop_front() {
        let annotations = vec![];
        write_ty_def(w, &ty, &annotations, ctx)?;

        all_tys.push(ty);
    }
    Ok(all_tys)
}

/// Generates a type definition.
#[rustfmt::skip::macros(writeln)]
#[rustfmt::skip::macros(write)]
pub fn write_ty_def(
    w: &mut impl Write,
    ty: &ir::Ty,
    _annotations: &[pr::Annotation],
    ctx: &mut Context,
) -> Result<(), std::fmt::Error> {
    let name = ty.name.as_ref().unwrap();

    writeln!(w)?;
    match &ty.kind {
        ir::TyKind::Primitive(_) | ir::TyKind::Array(_) => {
            writeln!(w, "@dataclasses.dataclass")?;
            writeln!(w, "class {name}:")?;
            writeln!(w, "    value: {}", ty_ref(ty, ctx))?;

            write_head_bytes(w, ty)?;
            writeln!(w)?;
            writeln!(w, "    @classmethod")?;
            writeln!(w, "    def decode(cls, buf: bytes) -> '{name}':")?;
            writeln!(w, "        return {name}({}.decode(buf))", ty_codec(ty, ctx))?;
            writeln!(w)?;
            writeln!(w, "    def encode_head(self, buf: lutra_bin.BytesMut) -> typing.Any:")?;
            writeln!(w, "        return {}.encode_head(self.value, buf)", ty_codec(ty, ctx))?;
            writeln!(w)?;
            writeln!(w, "    def encode_body(self, residual: typing.Any, buf: lutra_bin.BytesMut) -> typing.Any:")?;
            writeln!(w, "        return {}.encode_body(self.value, residual, buf)", ty_codec(ty, ctx))?;
        }

        ir::TyKind::Tuple(fields) => {
            writeln!(w, "@dataclasses.dataclass")?;
            writeln!(w, "class {}:", name)?;

            // fields definitions
            for (index, field) in fields.iter().enumerate() {
                let name = tuple_field_name(&field.name, index);

                writeln!(w, "    {name}: {}", ty_ref(&field.ty, ctx))?;
            }

            write_head_bytes(w, ty)?;

            // decode
            writeln!(w)?;
            writeln!(w, "    @classmethod")?;
            writeln!(w, "    def decode(cls, buf: bytes) -> '{name}':")?;
            writeln!(w, "        buf = memoryview(buf)")?;

            let offsets = layout::tuple_field_offsets(ty);
            for (index, field) in fields.iter().enumerate() {
                let buf = format!("buf[{}:]", offsets[index]);
                writeln!(w, "        f{index} = {}", ty_decode(&field.ty, &buf, ctx))?;
            }
            write!(w, "        return {name}(")?;
            for (index, _) in fields.iter().enumerate() {
                write!(w, "f{index}, ")?;
            }
            writeln!(w, ")\n")?;

            // encode_head
            writeln!(w, "    def encode_head(self, buf: lutra_bin.BytesMut) -> typing.Any:")?;
            writeln!(w, "        return (")?;
            for (index, field) in fields.iter().enumerate() {
                let name = tuple_field_name(&field.name, index);
                let val_ref = format!("self.{name}");
                write!(w, "            ",)?;
                writeln!(w, "{},", ty_encode_head(&field.ty, &val_ref, ctx))?;
            }
            writeln!(w, "        )")?;
            writeln!(w)?;

            // encode_body
            writeln!(w, "    def encode_body(self, residuals: typing.Any, buf: lutra_bin.BytesMut):")?;
            for (index, field) in fields.iter().enumerate() {
                let name = tuple_field_name(&field.name, index);
                let val_ref = format!("self.{name}");
                let res_ref = format!("residuals[{index}]");

                let encode_body = ty_encode_body(&field.ty, &val_ref, &res_ref, ctx);
                if !encode_body.is_empty() {
                    writeln!(w, "        {encode_body}")?;
                }
            }
        }

        ir::TyKind::Enum(_) => {
            writeln!(w, "class {name}:")?;

            write_head_bytes(w, ty)?;

            // decode
            writeln!(w)?;
            writeln!(w, "    @classmethod")?;
            writeln!(w, "    def decode(cls, buf: bytes) -> '{name}':")?;
            writeln!(w, "        return {name}()")?;

            // encode_head
            writeln!(w, "    def encode_head(self, buf: lutra_bin.BytesMut) -> typing.Any:")?;
            writeln!(w, "        pass")?;

            // encode_body
            writeln!(w, "    def encode_body(self, residuals: typing.Any, buf: lutra_bin.BytesMut):")?;
            writeln!(w, "        pass")?;
        }

        _ => unimplemented!(),
    }
    writeln!(w)?;

    Ok(())
}

fn write_head_bytes(w: &mut impl Write, ty: &ir::Ty) -> Result<(), std::fmt::Error> {
    let head_bytes = ty.layout.as_ref().unwrap().head_size.div_ceil(8);
    writeln!(w)?;
    writeln!(w, "    def head_bytes(self) -> int:")?;
    writeln!(w, "        return {head_bytes}")?;
    Ok(())
}

fn tuple_field_name(name: &Option<String>, index: usize) -> Cow<'_, str> {
    (name.as_ref())
        .map(|x| Cow::Borrowed(x.as_str()))
        .unwrap_or_else(|| format!("field{index}").into())
}

/// Reference to a python type
fn ty_ref(ty: &ir::Ty, ctx: &mut Context) -> Cow<'static, str> {
    match &ty.kind {
        ir::TyKind::Primitive(ir::TyPrimitive::bool) => "bool".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int8) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int16) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int32) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int64) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint8) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint16) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint32) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint64) => "int".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::float32) => "float".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::float64) => "float".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::text) => "str".into(),

        ir::TyKind::Array(items_ty) => format!("list[{}]", ty_ref(items_ty, ctx)).into(),

        ir::TyKind::Ident(ident) => {
            // TODO
            ident.0.last().unwrap().clone().into()
        }

        ir::TyKind::Tuple(_) | ir::TyKind::Enum(_) => {
            ctx.def_buffer.push_back(ty.clone());

            ty.name
                .clone()
                .unwrap_or_else(|| panic!("no name for {ty:?}"))
                .into()
        }

        _ => unimplemented!(),
    }
}

// Construct Codec class that can encode/decode the type
fn ty_codec(ty: &ir::Ty, ctx: &mut Context) -> Cow<'static, str> {
    match &ty.kind {
        ir::TyKind::Primitive(ir::TyPrimitive::bool) => "lutra_bin.BoolCodec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int8) => "lutra_bin.Int8Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int16) => "lutra_bin.Int16Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int32) => "lutra_bin.Int32Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::int64) => "lutra_bin.Int64Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint8) => "lutra_bin.Uint8Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint16) => "lutra_bin.Uint16Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint32) => "lutra_bin.Uint32Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::uint64) => "lutra_bin.Uint64Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::float32) => "lutra_bin.Float32Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::float64) => "lutra_bin.Float64Codec()".into(),
        ir::TyKind::Primitive(ir::TyPrimitive::text) => "lutra_bin.TextCodec()".into(),

        ir::TyKind::Array(item_ty) => {
            format!("lutra_bin.ArrayCodec({})", ty_codec(item_ty, ctx)).into()
        }

        ir::TyKind::Ident(_) | ir::TyKind::Tuple(_) | ir::TyKind::Enum(_) => ty_ref(ty, ctx),

        _ => unimplemented!(),
    }
}

fn ty_decode(ty: &ir::Ty, buf_ref: &str, ctx: &mut Context) -> String {
    match &ty.kind {
        ir::TyKind::Primitive(_) | ir::TyKind::Array(_) => {
            // these types are decoded into native (primitive) types, so they don't implement Encodable
            format!("{}.decode({buf_ref})", ty_codec(ty, ctx))
        }

        ir::TyKind::Ident(_) | ir::TyKind::Tuple(_) | ir::TyKind::Enum(_) => {
            format!("{}.decode({buf_ref})", ty_codec(ty, ctx))
        }

        _ => unimplemented!(),
    }
}

fn ty_encode_head(ty: &ir::Ty, val_ref: &str, ctx: &mut Context) -> String {
    match &ty.kind {
        ir::TyKind::Primitive(_) | ir::TyKind::Array(_) => {
            // these types use wrappers provided by lutra package, which need to be unwrapped
            format!("{}.encode_head({val_ref}, buf)", ty_codec(ty, ctx))
        }

        ir::TyKind::Tuple(_) | ir::TyKind::Enum(_) | ir::TyKind::Ident(_) => {
            format!("{val_ref}.encode_head(buf)")
        }

        _ => unimplemented!(),
    }
}

fn ty_encode_body(ty: &ir::Ty, val_ref: &str, residual_ref: &str, ctx: &mut Context) -> String {
    match &ty.kind {
        ir::TyKind::Primitive(ir::TyPrimitive::text) | ir::TyKind::Array(_) => {
            let codec = ty_codec(ty, ctx);
            format!("{codec}.encode_body({val_ref}, {residual_ref}, buf)")
        }

        ir::TyKind::Primitive(_) => String::new(),

        ir::TyKind::Tuple(_) | ir::TyKind::Enum(_) | ir::TyKind::Ident(_) => {
            format!("{val_ref}.encode_body({residual_ref}, buf)")
        }

        _ => unimplemented!(),
    }
}

fn write_sr_programs(
    w: &mut impl Write,
    functions: &[(&String, ir::TyFunction)],
    ctx: &mut Context,
) -> Result<(), std::fmt::Error> {
    if functions.is_empty() {
        return Ok(());
    }

    for (name, func) in functions {
        let mut fq_path = pr::Path::new(&ctx.current_rust_mod);
        fq_path.push((*name).clone());

        // compile
        let program = lutra_compiler::compile_to_sql(ctx.project, &fq_path);

        // encode to base85
        let mut buf = bytes::BytesMut::new();
        program.encode(&mut buf);
        let program_base85 = base85::encode(&buf);

        writeln!(w)?;
        writeln!(w, "@functools.cache")?;
        writeln!(w, "def {name}() -> lutra_bin.TypedProgram:")?;
        writeln!(w, "    return lutra_bin.TypedProgram(")?;
        writeln!(w, "        base64.b85decode(b'{program_base85}'),")?;
        writeln!(w, "        type(()),")?;
        writeln!(w, "        {},", ty_codec(&func.body, ctx))?;
        writeln!(w, "    )")?;
    }

    Ok(())
}
