from .common import Codec

class BytesMut:
    def __init__(self) -> None: ...
    def into_bytes(self) -> bytes: ...

class UnitCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> tuple[()]: ...
    def encode_head(self, value: tuple[()], buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: tuple[()], head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class BoolCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> bool: ...
    def encode_head(self, value: bool, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: bool, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Int8Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Int16Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Int32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Int64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Uint8Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Uint16Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Uint32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Uint64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: int, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Float32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> float: ...
    def encode_head(self, value: float, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: float, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class Float64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> float: ...
    def encode_head(self, value: float, buf: BytesMut) -> tuple[()]: ...
    def encode_body(
        self, value: float, head_residual: tuple[()], buf: BytesMut
    ) -> None: ...

class TextCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> str: ...
    def encode_head(self, value: str, buf: BytesMut) -> int: ...
    def encode_body(self, value: str, head_residual: int, buf: BytesMut) -> None: ...

class ArrayCodec[I: Codec]:
    def __init__(self, item_codec: I) -> None: ...
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> list: ...
    def encode_head(self, value: list, buf: BytesMut) -> int: ...
    def encode_body(self, value: list, head_residual: int, buf: BytesMut) -> None: ...

class EnumCodecHelper:
    def __init__(self, format: bytes) -> None: ...
    def decode_head(self, buf: bytes) -> tuple[int, int]: ...
    def encode_head_tag(self, tag: int, buf: BytesMut) -> int | None: ...
    def encode_head_padding(self, tag: int, buf: BytesMut) -> None: ...
    def encode_body_ptr(self, residual: int, buf: BytesMut) -> None: ...

class Ty:
    @staticmethod
    def decode(buf: bytes) -> Ty: ...
    def encode(self) -> bytes: ...
