# Type definitions for the Rust part of the package

import typing
from .. import Codec

class BytesMut:
    def __init__(self): ...
    def into_bytes(self) -> bytes: ...

class UnitCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> (): ...
    def encode_head(self, value: (), buf: BytesMut): ...
    def encode_body(self, value: (), head_residual: (), buf: BytesMut): ...

class BoolCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> bool: ...
    def encode_head(self, value: bool, buf: BytesMut): ...
    def encode_body(self, value: bool, head_residual: (), buf: BytesMut): ...

class Int8Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Int16Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Int32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Int64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Uint8Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Uint16Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Uint32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Uint64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: (), buf: BytesMut): ...

class Float32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> float: ...
    def encode_head(self, value: float, buf: BytesMut): ...
    def encode_body(self, value: float, head_residual: (), buf: BytesMut): ...

class Float64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> float: ...
    def encode_head(self, value: float, buf: BytesMut): ...
    def encode_body(self, value: float, head_residual: (), buf: BytesMut): ...

class TextCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> str: ...
    def encode_head(self, value: str, buf: BytesMut): ...
    def encode_body(self, value: str, head_residual: int, buf: BytesMut): ...

class ArrayCodec[I: Codec]:
    def __init__(self, item_codec: I): ...
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> list: ...
    def encode_head(self, value: list, buf: BytesMut): ...
    def encode_body(self, value: list, head_residual: int, buf: BytesMut): ...

class EnumCodecHelper:
    def __init__(self, format: bytes): ...
    def decode_head(self, buf: bytes) -> typing.Tuple[int, int]: ...
    def encode_head_tag(self, tag: int, buf: BytesMut) -> typing.Optional[int]: ...
    def encode_head_padding(self, tag: int, buf: BytesMut): ...
    def encode_body_ptr(self, residual: int, buf: BytesMut): ...
