import typing

class BytesMut:
    def __init__(self): ...
    def into_bytes(self) -> bytes: ...

class Codec[T](typing.Protocol):
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> T: ...
    def encode_head(self, value: T, buf: BytesMut) -> typing.Any: ...
    def encode_body(self, value: T, head_residual: typing.Any, buf: BytesMut): ...

class Encodable(typing.Protocol):
    @classmethod
    def decode(cls, buf: bytes) -> typing.Self: ...
    def encode_head(self, buf: BytesMut) -> typing.Any: ...
    def encode_body(self, head_residual: typing.Any, buf: BytesMut): ...

class BoolCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> bool: ...
    def encode_head(self, value: bool, buf: BytesMut): ...
    def encode_body(self, value: bool, head_residual: tuple[()], buf: BytesMut): ...

class Int8Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Int16Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Int32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Int64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Uint8Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Uint16Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Uint32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Uint64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> int: ...
    def encode_head(self, value: int, buf: BytesMut): ...
    def encode_body(self, value: int, head_residual: tuple[()], buf: BytesMut): ...

class Float32Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> float: ...
    def encode_head(self, value: float, buf: BytesMut): ...
    def encode_body(self, value: float, head_residual: tuple[()], buf: BytesMut): ...

class Float64Codec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> float: ...
    def encode_head(self, value: float, buf: BytesMut): ...
    def encode_body(self, value: float, head_residual: tuple[()], buf: BytesMut): ...

class TextCodec:
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> str: ...
    def encode_head(self, value: str, buf: BytesMut): ...
    def encode_body(self, value: str, head_residual: int, buf: BytesMut): ...

class ArrayCodec[I: Codec]:
    def __init__(self, item_codec: I): ...
    def head_bytes(self) -> int: ...
    def decode(self, buf: bytes) -> list: ...
    def encode_head(self, value: list, buf: BytesMut): ...
    def encode_body(self, value: list, head_residual: int, buf: BytesMut): ...

def decode_array[I: Encodable](
    item_type: typing.Type[I], item_head_bytes: int, buf: bytes
) -> list[I]: ...
def encode_array_head[I: Encodable](item: I, buf: BytesMut) -> int: ...
def encode_array_body[I: Encodable](item: I, head_residual: int, buf: BytesMut): ...

# Python part of the package

def encode[T: Encodable](obj: T) -> bytes: ...
def decode[T: Encodable](typ: type[T], buf: bytes) -> T: ...

class TypedProgram[I: Encodable, O: Encodable]:
    def __init__(
        self,
        program: bytes,
        input_ty: typing.Type[I],
        output_ty: typing.Type[O],
    ): ...
