ALTER VIEW ZTSI_REP.V_REP_DIG04_FCT_USERS_BY_LOCATION AS

/********************************************************************
								B2C	
	priprava podatkov o strankah in njihovem najnovejšem sso_id
********************************************************************/
-- DA POVEŽEMO CST_ID S SAMO ENIM SSO_ID (ACCOUNT) - TISTI, KI IMA NAJNOVEJŠE PODATKE O E_COMM IN SECURITY ID IN OSTALO, KAR SE RABI ZA FILTRE
WITH SSO_BASE AS (
	SELECT DISTINCT
		CST_ID,
		RGSTR_DT,
		ACCOUNT,
		GENDER_ID,
		AGE_RNG_ID,
		E_COMMUNICATION_ID,
		E_COMMUNICATION_DT,
		SECURITY_TIER_ID,
		SECURITY_TIER_GAINED_METHOD_ID
	FROM CORP_REP.V_REP_DIG04_FCT_SSO_ACCOUNTS
	WHERE 
		REALM = 1
		AND CST_ID IS NOT NULL 
		AND CST_ID <> ''
		--AND CST_ID = '300780945'
),

SSO_RANK AS (
	SELECT 
		*,
		RANK() OVER(PARTITION BY CST_ID ORDER BY RGSTR_DT DESC) AS RNK
	FROM SSO_BASE
),

SSO_E_COMM_RANK AS (
	SELECT
		CST_ID,
		RGSTR_DT,
		ACCOUNT,
		GENDER_ID,
		AGE_RNG_ID,
		E_COMMUNICATION_ID,
		E_COMMUNICATION_DT,
		SECURITY_TIER_ID,
		SECURITY_TIER_GAINED_METHOD_ID,
		ROW_NUMBER() OVER(PARTITION BY CST_ID ORDER BY E_COMMUNICATION_DT DESC) E_COMM_RNK --ni rank, ker ni nobenega patterna, da bi lahko še kaj uredila
	FROM SSO_RANK
	WHERE CST_ID IN (SELECT CST_ID FROM (
									SELECT CST_ID, COUNT(*) C
									FROM (SELECT * FROM SSO_RANK WHERE RNK = 1) X
									GROUP BY CST_ID HAVING COUNT(*) <>1
									) Y )
		AND RNK = 1
),

SSO_FINAL AS (
	SELECT *
	FROM SSO_RANK
	WHERE RNK = 1 
	AND CST_ID IN (SELECT CST_ID FROM (
									SELECT CST_ID, COUNT(*) C
									FROM (SELECT * FROM SSO_RANK WHERE RNK = 1) X
									GROUP BY CST_ID HAVING COUNT(*) = 1
									) Y )
	UNION ALL


	SELECT *
	FROM SSO_E_COMM_RANK
	WHERE E_COMM_RNK = 1 
),

-- DATUM PRVE REGISTRACIJE ZA POSAMEZEN CST_ID
SSO_RGSTR_DT AS (
	SELECT
		CST_ID,
		MIN(RGSTR_DT) RGSTR_DT
	FROM CORP_REP.V_REP_DIG04_FCT_SSO_ACCOUNTS F
	WHERE F.REALM = 1 -- SLOVENIJA
		AND F.CST_ID IS NOT NULL
		AND F.CST_ID <> ''
	GROUP BY CST_ID
),

/********************************************************************
								B2B		
			priprava podatkov o strankah in njihovih občinah
********************************************************************/
BASE AS (
	SELECT
		TAX_ID,
		DSC,
		FULL_NM,
		ST_DSC,
		RGON
	FROM ZTSI_DM.DIM_CST
	WHERE 
		TAX_ID IN (SELECT DISTINCT CAST(TAX_ID AS NVARCHAR) FROM ZTSI_REP.V_REP_DIG04_FCT_B2B_ACCESS)
		AND SRC_APL_ID = 1
		AND VLD_FLG = 1
		AND ACTV = 1
		AND TP_NM = 'PO'
),

RANKING AS (
	-- NAREDIM RANKING ČEZ PONOVITVE RGON-OV
	SELECT
		TAX_ID,
		RGON,
		RGON_APPEARANCE_COUNT,
		RANK() OVER(PARTITION BY TAX_ID ORDER BY RGON_APPEARANCE_COUNT DESC) AS RNK
	FROM (
		-- FILTRIRAM SE SAMO NA TISTE, KI IMAJO VEČ KOT EN RGON
		-- PREŠTEJEM KOLIKOKRAT SE EN RGON PONOVI ZA POSAMEZEN TAX_ID
		-- tukaj ne morem imet DSC in FULL_NM, ker se potem RGON ne sešteje lepo
		SELECT TAX_ID, RGON, COUNT(*) AS RGON_APPEARANCE_COUNT
		FROM BASE B
		WHERE B.TAX_ID IN (SELECT TAX_ID FROM (SELECT TAX_ID, COUNT(*) C FROM BASE GROUP BY TAX_ID) X WHERE C <> 1)
		GROUP BY TAX_ID, RGON
		) X
),

FILTERED AS (
	-- VZAMEM SAMO TISTI RGON, KI IMA NAJVEČ PONOVITEV
	SELECT * 
	FROM RANKING 
	WHERE RNK = 1
),

------- NA TEJ TOČKI SE ZAČNE UREJANJE TISTIH, KI IMAJO VEČ KOT EN RGON Z RNK = 1
VEC_RGONOV AS (
	-- SFILTRIRAM SE NA NAJKRAJŠI DSC (DA SE IZOGNEM PE IN SKLADIŠČEM)
	SELECT
		TAX_ID,
		RGON
	FROM (
		-- RANGIRAM RGONE PO DOLŽINI DSC
		-- ČE IMATA DVA ISTO DOLŽINO, VZAMEM PRVEGA (Z ROW_NUMBER() NAMESTO RANK())
		SELECT *, ROW_NUMBER() OVER(PARTITION BY TAX_ID ORDER BY DSC_LENGTH ASC) SHORTEST_DSC
		FROM (
			-- DOLOČIM DOLŽINO DSC
			SELECT
				TAX_ID,
				RGON,
				LEN(DSC) AS DSC_LENGTH
			FROM (
				-- IZBEREM TAKE, PRI KATERIH NE MOREM DOLOČIT ENEGA RGONA KOT GLAVNEGA
				-- DODAM DSC IN FULL_NM
				SELECT
					F.TAX_ID,
					F.RGON,
					B.DSC,
					B.FULL_NM
				FROM FILTERED F
				LEFT JOIN BASE B ON B.TAX_ID = F.TAX_ID AND F.RGON = B.RGON
				WHERE F.TAX_ID IN (SELECT TAX_ID FROM (SELECT TAX_ID, COUNT(*) NO_OF_RGONS FROM FILTERED GROUP BY TAX_ID HAVING COUNT(*) <> 1)X)
				) VEC_GLAVNIH_RGONOV
			) DOLZINA
		) RANGIRANJE
	WHERE RANGIRANJE.SHORTEST_DSC = 1
),

FINAL AS (
	-- TISTI, KI IMAJO ŽE IZ PRVE SAMO EN RGON
	SELECT
		B.TAX_ID,
		B.RGON
	FROM BASE B
	WHERE B.TAX_ID IN (SELECT TAX_ID FROM (SELECT TAX_ID, COUNT(*) C FROM BASE GROUP BY TAX_ID) X WHERE C = 1)

	UNION

	-- TISTI, KI IMAJO TOČNO EN RGON, KI IZSTOPA PO ŠTEVILU ZAPISOV
	SELECT 
		F.TAX_ID,
		F.RGON
	FROM FILTERED F
	WHERE F.TAX_ID NOT IN (SELECT V.TAX_ID FROM VEC_RGONOV V)

	UNION

	-- TISTI, KI NIMAJO LEADING RGONA, ZATO VZAMEM TISTEGA Z NAJKRAJŠIM DIM_CST.DSC
	SELECT
		V.TAX_ID,
		V.RGON
	FROM VEC_RGONOV V
),

B2B_USER_ACTIVITY AS (
	SELECT
		USER_AZURE_ID,
		MAX(ACCESS_DATE) AS ACCESS_DATE
	FROM ZTSI_REP.V_REP_DIG04_FCT_B2B_USER_ACTIVITY
	WHERE MODUL_ID IN (1,3)
	GROUP BY USER_AZURE_ID
),

/********************************************************************
								DRAJV		
********************************************************************/

MAX_TRIPSTART AS (
	SELECT 
		USERS AS DRAJV_USER_ID,
		MAX(TRIPSTART_DT) AS MAX_TRIPSTART_DT
	FROM ZTSI_REP.V_REP_DRAJV_FCT
	GROUP BY USERS
),
ALL_FINAL AS (

SELECT DISTINCT
	CAST(C.CST_ID AS INT) AS CST_ID,
	NULL AS AZURE_USER_ID,
	CAST(U.CREATED AS DATE) AS RGSTR_DT,
	CASE WHEN CAST(U.CREATED AS DATE) >= DATEADD(DAY, -91, GETDATE()) THEN 1 -- ALI JE OD PRVE REGISTRACIJE POTEKLO MANJ KOT 3 MESECE
		ELSE 0 END AS NEW_USER_FLAG,
	D.MAX_TRIPSTART_DT AS LAST_LOGIN,
	CASE
		WHEN D.MAX_TRIPSTART_DT >= DATEADD(DAY, -91, GETDATE()) THEN 1 -- IF MAX_TRIPSTART_DT IN LAST 3 MONTHS
		ELSE 0
	END AS ACTIVE_USER_FLAG, -- ALI JE V ZADNJIH 3 MESECIH VOZIL
	C.RGON,
	NULL AS B2B_MODUL_ID,
	NULL AS GENDER_ID,
	NULL AS AGE_RNG_ID,
	NULL AS E_COMMUNICATION_ID,
	NULL AS E_COMMUNICATION_DT,
	NULL AS SECURITY_TIER_ID,
	NULL AS SECURITY_TIER_GAINED_METHOD_ID,
	'DRAJV' AS SOURCE_APP
FROM ZTSI_REP.V_REP_DRAJV_FCT F
	LEFT JOIN MAX_TRIPSTART D ON F.USERS = D.DRAJV_USER_ID
	LEFT JOIN ZTSI_STG_DRAJV_BEH.DBO_USERS U ON F.USERS = U.ID
	LEFT JOIN ZTSI_STG_ITRIGLAV.SSO_SSO_USERPROFILE S ON U.SSOID = S.SSO_ID
	LEFT JOIN ZTSI_DM.DIM_CST C ON S.ASSETS_ID = C.NM AND C.VLD_FLG = 1 AND C.SRC_APL_ID = 1
WHERE 1=1
	AND S.SSO_ID IS NOT NULL -- ČE SO SAMO UPORABNIKI DRAJVA IN NE ITRIGLAVA, NE MOREMO DOBIT VEČ PODATKOV O NJIH
	AND C.CST_ID IS NOT NULL -- SO UPORABNIKI DRAJVA IN ITRIGLAVA, AMPAK NIMAJO SKLENJENIH ZAVAROVANJ - NE MOREMO DOBIT DODATNIH PODATKOV

UNION ALL

/********************************************************************
								B2C		
********************************************************************/

SELECT DISTINCT
	F.CST_ID,
	S.ACCOUNT AS AZURE_USER_ID,
	F.RGSTR_DT, 
	CASE
		WHEN F.RGSTR_DT >= DATEADD(DAY, -91, GETDATE()) THEN 1 -- IF REGISTERED LESS THAN 3 MONTHS AGO
		ELSE 0
	END AS NEW_USER_FLAG,
	CAST(MAX(U.LAST_LOGIN) AS DATE) AS LAST_LOGIN,
	CASE
		WHEN CAST(MAX(U.LAST_LOGIN) AS DATE) >= DATEADD(DAY, -91, GETDATE()) THEN 1 -- IF LAST LOGIN LESS THAN 3 MONTHS AGO
		ELSE 0
	END AS ACTIVE_USER_FLAG,
	C.RGON,
	NULL AS B2B_MODUL_ID,
	S.GENDER_ID,
	S.AGE_RNG_ID,
	S.E_COMMUNICATION_ID,
	S.E_COMMUNICATION_DT,
	S.SECURITY_TIER_ID,
	S.SECURITY_TIER_GAINED_METHOD_ID,
	'iTRIGLAV' AS SOURCE_APP
FROM SSO_RGSTR_DT F
	LEFT JOIN ZTSI_DM.DIM_CST C ON F.CST_ID = CAST(C.CST_ID AS INT) AND C.SRC_APL_ID = 1 AND C.VLD_FLG = 1
	LEFT JOIN SSO_FINAL S ON F.CST_ID = S.CST_ID
	LEFT JOIN ZTSI_STG_ITRIGLAV.SSO_SSO_USERPROFILE U ON S.ACCOUNT = U.SSO_ID
WHERE 
	C.RGON IS NOT NULL
	AND C.RGON <> 'N/P'
GROUP BY
	F.CST_ID,
	S.ACCOUNT,
	F.RGSTR_DT,
	C.RGON,
	S.GENDER_ID,
	S.AGE_RNG_ID,
	S.E_COMMUNICATION_ID,
	S.E_COMMUNICATION_DT,
	S.SECURITY_TIER_ID,
	S.SECURITY_TIER_GAINED_METHOD_ID

UNION ALL

/********************************************************************
								B2B		
********************************************************************/

SELECT DISTINCT
	NULL AS CST_ID,
	F.USER_AZURE_ID AS AZURE_USER_ID,
	F.RGST_DT AS RGSTR_DT,
	CASE
		WHEN F.RGST_DT >= DATEADD(DAY, -91, GETDATE()) THEN 1 -- IF REGISTERED LESS THAN 3 MONTHS AGO
		ELSE 0
	END AS NEW_USER_FLAG,
	A.ACCESS_DATE AS LAST_LOGIN,
	CASE
		WHEN A.ACCESS_DATE >= DATEADD(DAY, -91, GETDATE()) THEN 1 -- IF ACCESSED LESS THAN 3 MONTHS AGO
		ELSE 0
	END AS ACTIVE_USER_FLAG,
	D.RGON,
	F.MODUL_ID AS B2B_MODUL_ID,
	NULL AS GENDER_ID,
	NULL AS AGE_RNG_ID,
	NULL AS E_COMMUNICATION_ID,
	NULL AS E_COMMUNICATION_DT,
	NULL AS SECURITY_TIER_ID,
	NULL AS SECURITY_TIER_GAINED_METHOD_ID,
	'iTRIGLAV Poslovni' AS SOURCE_APP
FROM ZTSI_REP.V_REP_DIG04_FCT_B2B_ACCESS F
	LEFT JOIN FINAL D ON D.TAX_ID = CAST(F.TAX_ID AS NVARCHAR)
	LEFT JOIN B2B_USER_ACTIVITY A ON F.USER_AZURE_ID = A.USER_AZURE_ID
WHERE F.MODUL_ID IN (1,3) -- PDPZ IN KARTICA
	AND D.RGON IS NOT NULL

)

SELECT *
FROM ALL_FINAL
WHERE YEAR(RGSTR_DT) IN (2024, 2025)
AND YEAR(LAST_LOGIN) IN (2024, 2025)