experimental = ["benchmarks"]

[profile.default]
status-level = "slow"
fail-fast = false

[profile.overview]
status-level = "none"
final-status-level = "slow"
failure-output = "final"
fail-fast = false
