experimental = ["benchmarks"]

[profile.default]
status-level = "slow"
fail-fast = false

[profile.final-all]
status-level = "none"
final-status-level = "all"
failure-output = "never"
fail-fast = false
