_default:
    just --list

serve:
    zola serve

publish:
    zola build
    cd public && git init && git remote add origin ssh://git@codeberg.org/lutra/pages.git
    cd public && git add . && git commit -m 'publish' && git push origin main --force
