_default:
    just --list

generate-std:
    cargo run -p lutra-cli -- gen-docs --project=:std: docs/reference/language/std

serve:
    mprocs \
        'zola serve' \
        'zensical serve'

test:
    zola check

build:
    rm -rf public output
    zola build
    zensical build

publish:
    just build
    rsync --human-readable --progress --recursive --delete \
        output/ lutra-lang.org:/data/http
